# Generated by Django 2.2.3 on 2019-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0020_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('cooldown', models.IntegerField(default=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
