# Generated by Django 2.1.4 on 2019-07-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0020_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Group',
        ),
    ]
