# Generated by Django 2.1.4 on 2019-07-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0021_auto_20190722_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Group'),
        ),
        migrations.AddField(
            model_name='player',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Group'),
        ),
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Group'),
        ),
    ]
