# Generated by Django 2.2.3 on 2019-07-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0022_auto_20190722_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='group',
        ),
    ]
