# Generated by Django 2.2.3 on 2019-07-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0023_remove_room_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cooldown',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adventure.Group'),
        ),
        migrations.AlterField(
            model_name='player',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adventure.Group'),
        ),
    ]
