# Generated by Django 2.2.3 on 2019-07-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0024_auto_20190722_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Group'),
        ),
        migrations.AlterField(
            model_name='player',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Group'),
        ),
    ]
