# Generated by Django 2.2.3 on 2019-07-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0025_auto_20190722_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
        migrations.RemoveField(
            model_name='player',
            name='group',
        ),
    ]
